### ISSUE TITLE
Thank you and question

### ISSUE THREAD

**Issue by anthrolisp** [isene/hyperlist.vim#10]
I really love hyperlist. Thank you! I'm interested in compiling a list of similar software. Do you know of any others that are like it? Also, who or what inspired you to create it?

**Comment by isene** [comment]
I am glad you like it.

Here's the story behind HyperList:
In my consultancy work, I used a wide range of methodology to describe processes, projects, todo lists, situations, organizational charts, user interfaces, product ideas, philosophical concepts, etc. I used anything from Flowcharts, Fish-bone and Feynman diagrams to Venn, Petri net, Gantt and Wrnier Orr diagrams. There are problems with all of them - and a common problem is that they are graphical. Graphical representations are harder to co-create. And none of them can represent anything and everything. I wanted a way to represent any state (situation) or transition (motion - like processes) in a simple text-only solution. I started out in 2008 with the Warnier Orr diagrams, replaced the graphics with text and together with Egil Möller and Axel Liljencrantz created the first version of WOIM (Warnier-Orr-Isene-Möller) which a few years later became HyperList. It evolved into a methodology that can be used to describe anything. So far I have found nothing that cannot be represented in at least one way using HyperList.

Parallell with the HyperList methodology, I wanted software to make it easier to create, manipulate and maintain HyperLists. And since I use VIM for 99% of my text work (from writing e-mails, articles and books to editing fields in my browser [qutebrowser]), I decided to create a VIM plugin in 2012. And here we are.

As for similar programs - there are many todo-list programs and project management programs and more comprehensive solutions like Emacs Org mode, but I there are no other programs out there covering a methodology as wide as HyperList.
