### ISSUE TITLE
hyperlist.vim

### ISSUE THREAD

**Issue by rwmitchell** [isene/hyperlist.vim#11]
Where is the proper place to override the default settings for using external programs to open a file?
ie:    let b:imageprogram          = "feh"

On OS X, the simplest and possible the best solution is to use "open" to open all filetypes.  That allows the user's default system wide settings to take over.

More importantly, thank you for making this available.

Richard

**Comment by isene** [comment]
Thanks for the question.

I don't have a MacOSX, but try setting all the variables under s:UNIX (in the section USER DEFINED SETTINGS) to "open" - like this:

```
if s:UNIX
	let b:wordprocessingprogram = "open"
	let b:spreadsheetprogram    = "open"
	let b:presentationprogram   = "open"
	let b:pdfprogram            = "open"
	let b:imageprogram          = "open"
	let b:browserprogram        = "open"
endif
```

...and tell me if that works :-)

**Comment by rwmitchell** [comment]
That does work and already did that, however "git pull" then complains about local changes.

I made my change in:
`~/.vim/bundle/hyperlist.vim/syntax/hyperlist.vim`

Is there a better place to make that change?

**Comment by isene** [comment]
Ah - good point. I should make a better solution for user defined settings to source it from a custom file or something - because any changes you make to any of the files in the repo will be a local change that "git pull" will bitch about...

In the meantime, let "git pull" nag - I won't commit anything new until I also solve this in a nice way.

**Comment by isene** [comment]
I have a few ideas on how to handle this and could use your help to test it on MacOS. Take this file (rename to hyperlist.vim [since .vim files are not allowed as attachments on github]) drop it in your syntax directory and see if this makes sense (instructions are in the file). 
[hyperlist.txt](https://github.com/isene/hyperlist.vim/files/5008226/hyperlist.txt)

**Comment by isene** [comment]
No wait - there's a Much better way. Take this instead and simply set global varables in your vimrc as explained in the file (rename to hyperlist.vim as mentioned above).
[hyperlist.txt](https://github.com/isene/hyperlist.vim/files/5008636/hyperlist.txt)

**Comment by isene** [comment]
I went ahead and implemented the simplest solution. Several other important changes under the hood. Try the new version. Changelog:

```
Several important upgrades under the hood
Programs for opening files in references can now be set by
the user by setting the global variables in vimrc:
  g:wordprocessingprogram = ""
  g:spreadsheetprogram    = ""
  g:presentationprogram   = ""
  g:imageprogram          = ""
  g:pdfprogram            = ""
  g:browserprogram        = ""
```

**Comment by rwmitchell** [comment]
Changes work great!

I did have to preceded the above g: lines with "let".  I'm sure that is obvious to everyone.

**Comment by isene** [comment]
Great. I added the "let" in the docs and the Readme.md for clarity. Thanks for the feature request and for testing.
